### ISSUE TITLE
How bind the remove function to another function?

### ISSUE THREAD

**Issue by ReneFroger** [juanjux/evil-search-highlight-persist#15]
Thanks for sharing this package! I never could remember the <kbd>C-x</kbd><kbd><SPC></kbd> combination to quitthe search highlightings.

After reading about [advising functions](https://www.gnu.org/software/emacs/manual/html_node/elisp/Advising-Functions.html), I decided to bound it to the default </kbd>C-g<kbd>.

So I did the following:

     (advice-add 'keyboard-quit :after #'evil-search-highlight-persist-remove-all)

However, I never could it get working. Perhaps could you tell me where I went wrong in this? It would be appreicated by the way.

**Comment by ReneFroger** [comment]
Any update on this?

**Comment by ReneFroger** [comment]
It seems not?

**Comment by juanjux** [comment]
Sorry for the delay, my bogofilter was marking these as spam except the last message for some reason. The thing is that I'm not currently using Emacs, I went back to Vim so I only start emacs to test merge requests, basically. So with this and my lack of knowledge of emacs I can't help you.

**Comment by ReneFroger** [comment]
Thanks juanjux for your reply, it's appreciated!

**Comment by ReneFroger** [comment]
For future readers:

    (defun quit-and-exit-persistent-hl ()
        (interactive)
        (evil-search-highlight-persist-remove-all)
        (keyboard-quit)
        )

And then

    (global-set-key (kbd "C-g") 'quit-and-exit-persistent-hl)
